### ISSUE TITLE
Uncaught Error: Illegal wire type of unknown field 0 in Message 

### ISSUE THREAD

**Issue by seanmavley** [google/gtfs-realtime-bindings#18]
I understand this package is for node. I want to use this in my angular project, how do I proceed? Is there a way I can use it?

**Comment by seanmavley** [comment]
Using Browserify, however throwing an error:

```
var requestSettings = {
  method: 'GET',
  url: 'http://localhost:3000/data/addisoncounty-vt-us.zip',
  encoding: null
};
request(requestSettings, function (error, response, body) {
  if (!error && response.statusCode == 200) {
    var feed = GtfsRealtimeBindings.FeedMessage.decode(body);
    feed.entity.forEach(function(entity) {
      if (entity.trip_update) {
        console.log(entity.trip_update);
      }
    });
  }
});
```
Then I get this error:
`Uncaught Error: Illegal wire type of unknown field 0 in Message .transit_realtime.FeedMessage#decode: 3`

**Comment by barbeau** [comment]
@seanmavley Looks like you're trying to read a GTFS zip file (schedule data), not a GTFS-realtime feed (which is in a protocol buffer format).  Could you please try reading your agency's GTFS-realtime feed and then let us know if you still have problems?

**Comment by rickstergg** [comment]
I ran into the same issue but it was because I was using https instead of http like my agency specified.
