### ISSUE TITLE
inserting gtds-realtime-bindings in a new Maven project

### ISSUE THREAD

**Issue by XavierPrudent** [google/gtfs-realtime-bindings#22]
Hello,

I started a new Maven project, and inserted the content you gave for the dependencies inside the pom.xml.

But while creating the package (mvn package) the compilation crashed because of duplicated groupId and artifactId (from my project on one side, and from gtfs-realtime-bindings on the other side). Trying to remove one or the other duplicate did not help.
Am I missing something on how to include gtfs-rt-b in a maven package?
Thanks in advance,

regards,
Xavier

**Comment by barbeau** [comment]
@XavierPrudent Your project should have it's own groupId and artifactId at the top of your pom.xml file (NOT within the `<dependencies>` section) - these fields can have whatever values you want (e.g., `com.abc.123` and `com.abc.123.myapp`).  The gtfs-realtime-bindings snippet should only appear within the `<dependencies>` section of your pom.xml, and you should only have one `<dependencies>` section within your pom.xml.

Please give that a try and let me know if you still have problems.

**Comment by XavierPrudent** [comment]
Thank you Sean. Eventually I preferred re-implementing the real time generator.
