### ISSUE TITLE
Update to GTFS-rt v2.0

### ISSUE THREAD

**Issue by barbeau** [google/gtfs-realtime-bindings#26]
~~The reference [gtfs-realtime.proto](https://github.com/google/transit/blob/master/gtfs-realtime/proto/gtfs-realtime.proto) is now at v2, while the version in this repo is still at v1.~~ (Correction - the value of `gtfs_realtime_version` field in gtfs-realtime.proto doesn't need to change for GTFS-realtime v2.0 or any future version - see below comments in this thread).

I'm not sure if this requires that the bindings actually be regenerated (as no data structures changed) - if so, see bindings updating instructions at https://github.com/google/gtfs-realtime-bindings/blob/master/UPDATING.md.

An aside - should we remove gtfs-realtime.proto from this repo to avoid having two sources of truth?  

More extreme options include moving these bindings into the [google/transit repo](https://github.com/google/transit) where the spec lives, or using [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

It would be nice if this library also enforced the v2.0 semantics so things like `FeedHeader.timestamp` were considered mandatory, and the `Builder` would fail if this value wasn't provided for a v2.0 feed.

**Comment by RachM** [comment]
+1 to avoiding gtfs-realtime.proto from this repo.

I'd prefer to keep the bindings separate from the spec repo. Git submodules sounds like it could work.

**Comment by barbeau** [comment]
I'm closing this, as the bindings don't need to be updated for GTFS-rt v2.
