### ISSUE TITLE
Error during a GET request

### ISSUE THREAD

**Issue by Asher978** [google/gtfs-realtime-bindings#27]
Hello, 

I am using a get request to fetch the GTFS realtime data from NYC MTA.  Please see the snippet of my code ..... 

` let getData = (req, res, next) => {
    fetch(`http://datamine.mta.info/mta_esi.php?key=${MTA_API}&feed_id=${req.body.field_id}`)
    .then(fetchRes => {
      console.log(fetchRes.body);
      var feed = GtfsRealtimeBindings.transit_realtime.FeedMessage.decode(fetchRes.body);
      feed.entity.forEach(function(entity) {
        if (entity.trip_update) {
          console.log(entity.trip_update);
        }
      });
      console.log(feed);
      // return feed;
      next();
    }).then(jsonRes => {
      res.locals.mta = jsonRes
      next();
     }).catch(err => {
       console.log(err);
     })
   }`

i keep getting this error message:
`TypeError: Cannot read property 'FeedMessage' of undefined`

Any idea what might be wrong? I am trying to parse the GTFS data from MTA.

**Comment by Asher978** [comment]
fixed my own error. No worries
thanks

**Comment by VictorioBerra** [comment]
@Asher978 I copied and pasted the code from the README and am getting this exact same error.

Can you please update us with how you fixed your error?
