### ISSUE TITLE
Unexpected End group Tag

### ISSUE THREAD

**Issue by Gariantroll** [google/gtfs-realtime-bindings#34]
I am getting error "unexpected end-group tag".  I catch this error in an exception and then I loop the function back over to grab new data.  I thought I could live this way , but it seems after a couple of hours or maybe even days, the program freezes.  I am looking for a solution, but I am wondering if this has something to with the "unexpected end-group tag" or if i am just pulling two much.  I am pulling data every 20 seconds now.  I am running on a RPi 2B.  Does any body have any ideas?

**Comment by barbeau** [comment]
@Gariantroll Could you please give more information about the GTFS-realtime feed you're using, and the GTFS-realtime language bindings library you're using?

**Comment by Gariantroll** [comment]
Oh man, I wrote this issue so long ago I had to remember what the solution was when I found it.  I think it was something wrong with my Pi’s internet connection.  I think I have to look into to guarantee that was the issue.  Sorry, it was a while ago.

**Comment by barbeau** [comment]
@Gariantroll ok, thanks. I'm going to close this issue for now but please reopen if you can provide more info.
