### ISSUE TITLE
How to convert VehiclePosition to TripUpdate?

### ISSUE THREAD

**Issue by wowkin2** [google/gtfs-realtime-bindings#36]
Is there any possible way how to convert GTFS VehiclePosition + GTFS Static to TripUpdate?
Want to calculate real time to arrival and create new feed.
If not using this library, maybe anybody here knows something to do that?

**Comment by cwh711** [comment]
Generally that "conversion" is done by specific companies (like NextBus or Swiftly) that have complex proprietary algorithms for generating TripUpdates from positions and static schedules. You *could* do some calculations of distance to the stop and assume a certain speed to get an arrival time, but those times would be very rough estimates.

**Comment by barbeau** [comment]
@wowkin2 I'd suggest checking out TheTransitClock, which is an OSS project that generates GTFS-rt TripUpdates from GTFS-rt VehiclePositions + GTFS feeds (i.e., generates predictions from vehicle positions):
https://thetransitclock.github.io/
