### ISSUE TITLE
Support for Go

### ISSUE THREAD

**Issue by scottlacy** [google/gtfs-realtime-bindings#4]
Our shop uses Python for much of our front-end web development, but our lower-level transit integrations are written exclusively in Go. Would be great to integrate with GTFS-Realtime via Go.

**Comment by zhaostu** [comment]
+1

**Comment by idupree** [comment]
+1

**Comment by zhaostu** [comment]
Because GTFS-realtime is protocol buffer, I figured that it was very easy to generate Go bindings from the proto file: https://developers.google.com/transit/gtfs-realtime/gtfs-realtime-proto?hl=en

**Comment by daisuke-nomura** [comment]
+1

**Comment by idupree** [comment]
@zhaostu It is easy to generate gtfs-realtime.pb.go itself (install per https://github.com/golang/protobuf#installation then `protoc --go_out=. gtfs-realtime.proto`), but judging by the other things in this gtfs-realtime-bindings repository, you also have to figure out how to write tests and integrate it with Go's package system.  (I'm too new at Go to know what the right conventions are for that.)

**Comment by egorich239** [comment]
Not sure what would be the packaging/build system for Go, but if this is resolved, then just throw a pull request: https://github.com/google/gtfs-realtime-bindings#other-languages
