### ISSUE TITLE
Request For Actual Example Start To Finish Using Python Based Bindings

### ISSUE THREAD

**Issue by SBanya** [google/gtfs-realtime-bindings#40]
Hello,

I would like to request for a Google team to create a GTFS-realtime-bindings example for Python 3 based bindings from start to finish.

The example provided doesn't even scratch the surface regarding this issue, so please help beginners like myself to be able to implement GTFS related data (such as those given by NYC MTA) for projects.

I stress this because major city transit data feeds are in GTFS format, yet the example provided doesn't even help manipulate a real world example for it.

Thanks.

**Comment by barbeau** [comment]
@SBanya A complete example that ingests and integrates GTFS and GTFS-realtime into an in-memory data model is beyond the scope of this repo (this repo handles GTFS-realtime only), but I'd suggest checking out https://github.com/CUTR-at-USF/gtfsrdb and https://github.com/OpenTransitTools/gtfsdb, which may give you an idea of how Python can be used to insert GTFS and GTFS-realtime into a database.
