### ISSUE TITLE
Desearilizing feed

### ISSUE THREAD

**Issue by Spookenator** [google/gtfs-realtime-bindings#8]
Hi, i keep getting this error when trying to consume a feed 
    No transit_realtime.TripDescriptor+ScheduleRelationship enum is mapped to the wire-value 5

The feed i am intrested in is:
"https://gtfsrt.api.translink.com.au/feed"

could you assist?

**Comment by magdalar** [comment]
There is indeed no wire-value 5 defined in that enum, so technically, the
feed is invalid. That said, I suspect your protobuffer parser has a means
to ignore that error, or map the value to the default value (enum value 0),
and go about its business. You'd need to provide additional details for us
to provide you help on that, though -- such as which language you're even
using :)

Cheers,
-- Eric

**Comment by Spookenator** [comment]
Hey Eric,
Jah now i feel like an idiot hehe :P;
I am using the .net parser, i am teribbly new to the protobuff stack so sorry for not being able to provide you with a more detailed technical approach to my problem.

**Comment by brendancosmanmammoth** [comment]
I have the same issue with Translink's feed. I have a forked version of this project on my personal account; I'll find some time today to share the code snippet that I added as a workaround.

**Comment by BrendanCosman** [comment]
Spook: sorry for the delay. Here are the changes I needed to make to parse Translink's feed.

https://github.com/google/gtfs-realtime-bindings/compare/master...BrendanCosman:patch-1

 As Eric noted, Translink's feed is non-compliant / invalid, so these changes should be made in your project; I assume that the base project will not and should not be changed to adapt to Translink's non-compliant feed.

You'll probably find a few other places where you need to adapt to non-compliant data (in the static feed). Let me know if you come up against anything that you can't work out, I have a private side project that is using that data so I've worked through _most_ of the issues, and I don't mind helping what may end up being a competing service ;)
