### ISSUE TITLE
Support for R

### ISSUE THREAD

**Issue by Robinlovelace** [google/gtfs-realtime-bindings#9]
This will be very useful for academic and research-focussed transport planners.

My package co-author @richardellison has added gtfs import functionality:
https://github.com/ropensci/stplanr/pull/34

Could that could provide a basis for official support?

**Comment by egorich239** [comment]
If I read it correctly, the linked project concerns GTFS, while this
repository is about GTFS Real-time bindings.

Am 22.12.2015 9:17 vorm. schrieb "Robin" <notifications@github.com>:
>
> This will be very useful for academic and research-focussed transport
planners.

**Comment by Robinlovelace** [comment]
Yes - correct.

I assumed this included official support for GTFS - is there another repo for that?

**Comment by egorich239** [comment]
@Robinlovelace Not that I know of. Maybe @bdferris would know.
